version: '3.4'

services:
  splitter:
    image: systemgenesis0/splitter
    restart: unless-stopped
    ports:
      - 9001:9001
    env_file: variables.env
    volumes:
      - ./dataSources.js:/usr/src/app/dist/config/dataSources.js
      - ./key.pem:/usr/src/app/dist/key.pem
    depends_on:
      - redis
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  mocksKart:
    image: systemgenesis0/mock
    restart: unless-stopped
    env_file: mock.env
    volumes:
      - ./key.pem:/dist/key.pem
      - ./key.pem:/dist/key/key.pem
    ports:
      - 7700:7700

  redis:
    image: bitnami/redis:latest
    user: root
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

  basicmatch:
    image: systemgenesis0/basic_match
    env_file: basic_match.env
    volumes:
      - ./volumes/fieldNames.js:/usr/src/app/dist/config/fieldNames.js
      - ./volumes/basicMatch.enums.js:/usr/src/app/dist/config/enums.js
    depends_on:
      - splitter
      - rabbit

  buildentity:
    image: systemgenesis0/build_entity
    restart: unless-stopped
    env_file: buildEntities.env
    depends_on:
      - rabbit

  buildrogd:
    image: systemgenesis0/build_rogd
    restart: unless-stopped
    env_file: build_rogd.env
    volumes:
      - ./volumes/fieldNames.js:/usr/src/app/dist/config/fieldNames.js
      - ./volumes/buildROGD.db_enums.js:/usr/src/app/dist/config/db_enums.js
    depends_on:
      - rabbit

  # creatergbe:
  #   image: systemgenesis0/create_rgbe
  #   restart: unless-stopped
  #   env_file: creatergbe.env
  #   volumes:
  #     - ./key.pem:/dist/key.pem
  #     - ./key.pem:/dist/key/key.pem
  #   depends_on:
  #     - rabbit

  selector:
    image: systemgenesis0/selector
    restart: unless-stopped
    env_file: selector.env
    depends_on:
      - rabbit

  taskmanager:
    image: systemgenesis0/taskmanager
    restart: unless-stopped
    env_file: taskmanager.env
    volumes:
      - ./key.pem:/dist/key.pem
      - ./key.pem:/dist/key/key.pem
    ports:
      - 7706:7706
    depends_on:
      - redis
      - rabbit

  mergesapi:
    image: systemgenesis0/merges_api
    restart: unless-stopped
    env_file: mergesAPI.env
    volumes:
      - ./volumes/mergesAPI.sources.js:/usr/src/app/dist/config/sources.js
    ports:
      - 6060:6060
    depends_on:
      - rabbit

  mongo:
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - './data/db:/data/db'

  merger:
    image: systemgenesis0/merger
    restart: unless-stopped
    env_file: merger.env
    depends_on:
      - rabbit
      # - mongo

  mirror:
    image: systemgenesis0/mirror
    restart: unless-stopped
    env_file: mirror.env
    depends_on:
      - mongo

  black_list:
    image: systemgenesis0/black_list
    restart: unless-stopped
    env_file: black_list.env
    depends_on:
      - rabbit
      - mongo

volumes:
  redis_data:
    driver: local
