version: '3.4'

services:
  splitter:
    image: tommyafek/splitter
    restart: unless-stopped
    ports:
      - 9001:9001
    env_file: variables.env
    volumes:
      - ./dataSources.js:/usr/src/app/dist/config/dataSources.js
      - ./key.pem:/usr/src/app/dist/config/key.pem
    depends_on:
      - redis
      - rabbit

  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - 5672:5672
      - 15672:15672

  mocksKart:
    image: tommyafek/mock
    restart: unless-stopped
    env_file: mock.env
    ports:
      - 7700:7700

  redis:
    image: bitnami/redis:latest
    user: root
    restart: unless-stopped
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data

  basicmatch:
    image: tommyafek/basic_match:latest
    env_file: basic_match.env
    volumes:
      - ./volumes/fieldNames.js:/usr/src/app/dist/config/fieldNames.js
      - ./volumes/basicMatch.enums.js:/usr/src/app/dist/config/enums.js
    depends_on:
      - splitter
      - rabbit

  buildentity:
    image: tommyafek/build_entity
    restart: unless-stopped
    env_file: buildEntities.env
    depends_on:
      - rabbit

  buildrogd:
    image: tommyafek/build_rogd
    restart: unless-stopped
    env_file: build_rogd.env
    volumes:
      - ./volumes/fieldNames.js:/usr/src/app/dist/config/fieldNames.js
      - ./volumes/buildROGD.db_enums.js:/usr/src/app/dist/config/db_enums.js
    depends_on:
      - rabbit

  creatergbe:
    image: tommyafek/create_rgbe
    restart: unless-stopped
    env_file: creatergbe.env
    depends_on:
      - rabbit

  selector:
    image: tommyafek/selector
    restart: unless-stopped
    env_file: selector.env
    depends_on:
      - rabbit

  taskmanager:
    image: tommyafek/taskmanager:latest
    restart: unless-stopped
    env_file: taskmanager.env
    ports:
      - 7706:7706
    depends_on:
      - redis
      - rabbit

  mergesapi:
    image: tommyafek/merges_api
    restart: unless-stopped
    env_file: mergesAPI.env
    volumes:
      - ./volumes/mergesAPI.sources.js:/usr/src/app/dist/config/sources.js
    ports:
      - 6060:6060
    depends_on:
      - rabbit
      - mongo

  mongo:
    image: bitnami/mongodb:latest
    ports:
      - 27017:27017
    volumes:
      - './data/db:/data/db'

volumes:
  redis_data:
    driver: local
